# Generated by Django 6.0.6 on 2026-06-18 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(help_text='URL用の文字列（例: tops）', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='商品名')),
                ('description', models.TextField(verbose_name='商品説明')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='メイン画像')),
                ('is_available', models.BooleanField(default=True, verbose_name='販売中か（在庫あり）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='カテゴリ')),
            ],
        ),
    ]
